- hosts: master
  become: yes
  gather_facts: false
  tasks:
    - name: Copy file with owner and permissions
      ansible.builtin.copy:
        src: argo.sh
        dest: argo.sh
        mode: '0755'