- hosts: controller
  become: yes
  gather_facts: false
  tasks:
    - name: Copy file with owner and permissions
      when: install_argo == 'true'
      ansible.builtin.copy:
        src: ../files/argo.sh
        dest: argo.sh
        mode: '0755'
