- name: Install dependencies
  import_playbook: kube-dependencies.yml

- name: Initialize controller
  import_playbook: controller.yml

- name: Connect worker node to main node
  import_playbook: workers.yml

- name: Install Argo
  import_playbook: argo.yml
  when: install_argo == 'true'
